<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <RootNamespace>ClipSave.WindowsBackdrop</RootNamespace>
    <AssemblyName>clipsave_windows_backdrop</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <WindowsPackageType>None</WindowsPackageType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <PropertyGroup>
    <BackdropPackageRoot Condition="'$(RestorePackagesPath)' != ''">$(RestorePackagesPath)</BackdropPackageRoot>
    <BackdropPackageRoot Condition="'$(BackdropPackageRoot)' == ''">$(NuGetPackageRoot)</BackdropPackageRoot>
    <Win2DPackageRoot>$([System.IO.Path]::Combine('$(BackdropPackageRoot)', 'win2d.uwp', '1.28.3'))</Win2DPackageRoot>
    <VCRTForwardersPackageRoot>$([System.IO.Path]::Combine('$(BackdropPackageRoot)', 'microsoft.vcrtforwarders.140', '1.1.0'))</VCRTForwardersPackageRoot>
  </PropertyGroup>
  <ItemGroup>
    <PackageDownload Include="Win2D.uwp" Version="[1.28.3]" />
    <PackageDownload Include="Microsoft.VCRTForwarders.140" Version="[1.1.0]" />
    <Reference Include="Microsoft.Graphics.Canvas.Interop">
      <HintPath>$(Win2DPackageRoot)\lib\net8.0-windows10.0.19041.0\Microsoft.Graphics.Canvas.Interop.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <None
      Include="$(Win2DPackageRoot)\runtimes\win-x64\native\Microsoft.Graphics.Canvas.dll"
      Link="Microsoft.Graphics.Canvas.dll"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest" />
    <None
      Include="$(VCRTForwardersPackageRoot)\runtimes\win-x64\native\release\msvcp140_app.dll"
      Link="msvcp140_app.dll"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest" />
    <None
      Include="$(VCRTForwardersPackageRoot)\runtimes\win-x64\native\release\vcruntime140_1_app.dll"
      Link="vcruntime140_1_app.dll"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest" />
    <None
      Include="$(VCRTForwardersPackageRoot)\runtimes\win-x64\native\release\vcruntime140_app.dll"
      Link="vcruntime140_app.dll"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
